### ISSUE TITLE
Has fleep been abandoned?

### ISSUE THREAD

**Issue by NebularNerd** [floyernick/fleep#20]
I was looking for a way for Python to identify files and this seems to get the most hits on the net, however, it looks like it was abandoned some time ago. 

Can anyone confirm if it's no longer being actively maintained?

**Comment by egeres** [comment]
I'm not sure about all the functionalities implemented by fleep, but there is a tool called "libmagic" aimed to identify the contents of a file. It that has a maintained python wrapper: https://github.com/ahupp/python-magic, maybe it helps!

**Comment by NebularNerd** [comment]
There is also [PureMagic](/cdgriffith/puremagic) which I found a day or two after. That is being very actively developed, I made a request about [matching files with split fingerprints](/cdgriffith/puremagic/issues/46#issue-2110599323) and after a brief conversation it was added to the code base.

I'll close this as completed.
